### ISSUE TITLE
Error Running the result

### ISSUE THREAD

**Issue by NisarAhmedKhan** [aksiksi/dubizzle#1]
Firstly, thank you so much for creating this project. I really believe this has a lot of potential..

I am looking to query the property section (Im looking for a 2 bedroom apartment in Dubai). Please let me know if I can help you with the project in anyway.

I believe there is something wrong with the date calculation in the script. I get the following error while running the example:

> > > results = dubizzle.search(keyword='altima', country='uae', city='dubai', sec
> > > tion='motors',
> > > ...                           category='cars', make='nissan', min_year=2007, num
> > > _results='all')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 2, in <module>
> > >   File "C:\Python27\lib\site-packages\dubizzle\shortcuts.py", line 14, in search

```
results = raw.fetch()
```

  File "C:\Python27\lib\site-packages\dubizzle\uae.py", line 141, in fetch
    return self.parse(raw_results)
  File "C:\Python27\lib\site-packages\dubizzle\uae.py", line 152, in parse
    u'date': parse_date(result.select('.date')[0].text.strip()),
  File "C:\Python27\lib\site-packages\dubizzle\helpers.py", line 39, in parse_da
te
    day, month, year = re.findall(r'(\d+)\w+ (\w+) (\w+)', date)[0]
IndexError: list index out of range

Regards,
Nisar (0506449653)

**Comment by aksiksi** [comment]
Thanks for taking the time to open an issue! I will have a look at this and fix it as soon as I can. It probably is caused by a small change in Dubizzle's UI. A project like this will always be susceptible to break when such changes are made unfortunately.

As for the project, you might have noticed that I really haven't done much work on it in quite some time. I was looking through the code a few weeks ago and felt that it needs a general rewrite and more support for other categories and not only motors. I also would like to port it to Python 3.

I may start working on that soon. Do you have experience with Python?

**Comment by NisarAhmedKhan** [comment]
I'm basically a VB.NET developer.. just started with Python, and love the speed and simplicity.

I can see you've done some really clever regular expression hacks.. I'm interested in the property rentals for the time being.. and would love to help you with the project.

Please feel free to shoot me an email on nisarkhan@gmail.com, and we can take this further.

Nisar

**Comment by aksiksi** [comment]
This should now be fixed. I've yet to update the package via PyPI however.
