### ISSUE TITLE
unable to fetch certain details

### ISSUE THREAD

**Issue by ninjatrench** [aksiksi/dubizzle#2]
In dubizzle I was unable to fetch details like
No. Of Cylinders, Transmission Type etc etc
I can see them defined in code in uae.py but not able to get in final results.
Another thing it throws ArrayIndexOutOfRange error may be because they seem to have changed their date format.
Anyways, it would be very kind if you could help.
Thanks

**Comment by aksiksi** [comment]
Please post the stack trace in each case so I can see the exact exceptions. Also, did you install it via PyPI? If yes, please clone this repo and try the same input. Tell me what happens.

**Comment by aksiksi** [comment]
The issue should be fixed in the latest commits.

**Comment by ninjatrench** [comment]
While scrapping from *.dubizzle.com/motors/used-cars/ I was only able to scrape upto 40pages, Can you suggest any workaround so as to get all the cars ?

**Comment by aksiksi** [comment]
I'd guess the issue would be throttling by Dubizzle. If they see an IP making too many requests in a short amount of time, they will probably prevent you from making more.

The best way to avoid this is to have a delay between each request. I'm actually planning on a complete rewrite of this library. I'll be sure to add some simple anti-throttling features once I get around to doing it.

**Comment by ninjatrench** [comment]
Sounds amazing, I would like to contribute, I have already written code for dumping scrapped data into Database.

**Comment by aksiksi** [comment]
That would be great :smile: One thing that can definitely improve with this library is support for search options for categories other than Motors. 

Before on Dubizzle, when you changed the search options in the sidebar, a request was made to the server that simply returned the new form's HTML. Now they've setup a simple JSON endpoint ex: http://dubizzle.com/classified/get_category_models/CL/?site=2.

So now you can find the codes for each category in a more straightforward way instead of writing them manually like I did when I wrote this. With the rewrite, we can probably provide a class or function that the user can use to fetch all categories from all Dubizzle sites and save them to a JSON file for future use. We could also setup a simple API on Heroku or Google App Engine that will return all categories and codes on Dubizzle that can be used by the library.

Of course, if you have any ideas yourself, feel free to suggest them and we can discuss. With two people working on this, I think it can be a much more polished library than it is now :stuck_out_tongue:

**Comment by ninjatrench** [comment]
I have idea of writing it from scratch and also adding sqlalchemy support to directly dump scrapped data into the database or in mongoDB

**Comment by aksiksi** [comment]
It will be better to allow the user to decide how he/she would like to save the data. I think the role of this API should simply be retrieval of data from Dubizzle in a JSON-like format.
